experiments:
  - name: "dog_nonexpert_raw"
    expert_type: "nonexpert"
    use_raw_format: true
    animal_type: "dog"
    models:
      - "gpt-4o-mini"
      - "claude-3-haiku"
      - "gemini-2.0-flash"
      - "gemma-3-4b"
      - "qwen-2.5-7b"
      - "exaone-3.5-7.8b"
  - name: "cat_nonexpert_raw"
    expert_type: "nonexpert"
    use_raw_format: true
    animal_type: "cat"
    models:
      - "gpt-4o-mini"
      - "claude-3-haiku"
      - "gemini-2.0-flash"
      - "gemma-3-4b"
      - "qwen-2.5-7b"
      - "exaone-3.5-7.8b"

training_args:
  num_train_epochs: 1
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 4
  gradient_checkpointing: True
  learning_rate: 0.00005
  weight_decay: 0.01
  bf16: True
  logging_steps: 500
  eval_strategy: "steps"
  eval_steps: 500
  save_strategy: "steps"
  save_steps: 500
  load_best_model_at_end: False
  metric_for_best_model: "eval_loss"
  greater_is_better: False
  push_to_hub: False
  report_to: "wandb"
  save_total_limit: 3