training_args:
  num_train_epochs: 2
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 4
  gradient_checkpointing: True
  learning_rate: 0.00005
  weight_decay: 0.01
  bf16: True
  logging_steps: 500
  eval_strategy: "epoch"
  save_strategy: "epoch"
  load_best_model_at_end: False
  metric_for_best_model: "eval_loss"
  greater_is_better: False
  push_to_hub: False
  report_to: "wandb"
  save_total_limit: 3